name: OpenTK GLFW Redistributable

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ubuntu-latest
    container: debian:oldoldstable
    strategy:
      fail-fast: true

    steps:
    - name: Install X11 dependencies
      run: |
        apt-get update
        apt-get install -y xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
    - name: Install build dependencies
      run: |
        apt-get install -y curl wget git cmake
        VERSION_ID=$(awk -F= '/^VERSION_ID=/{gsub(/"/, "", $2); print $2}' /etc/os-release)
        wget -q https://packages.microsoft.com/config/debian/$VERSION_ID/packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        apt-get update
        apt-get install -y powershell
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Download dependencies and create Nuget Package
      run: ./make_nuget.ps1 "" ${{ github.run_number }}
      shell: pwsh
    - uses: actions/upload-artifact@v3
      with:
        name: NugetPackage
        path: ./artifacts/*.nupkg
    - name: Deploy Nuget Package
      run: dotnet nuget push ./artifacts/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
